import { defineConfig } from "oxlint";
import antiSlop from "ultracite/oxlint/anti-slop";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";

/*
 * The `ultracite/oxlint/js-plugins` presets are left off deliberately.
 * `github` and `sonarjs` fail to load at all: both reach @typescript-eslint →
 * ts-api-utils, which reads `ts.SyntaxKind.Intrinsic` and so cannot run against
 * the typescript@7 this repo pins.
 */
export default defineConfig({
  extends: [antiSlop, core, next, react],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by `shadcn add` and by the Rare UI registry: owned by the
    // CLI, not by hand, so the project's own conventions do not apply.
    "apps/dashboard/components/ui/**",
  ],
});
